// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hardajrbpoedlfyaqzcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhcmRhanJicG9lZGxmeWFxemNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzMzODQsImV4cCI6MjA2NzMwOTM4NH0._Xfqexg59GvP8kMJ_hwmbMPjbzgBzbVetCUDF3R2LNs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});